import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProviders } from "@/components/providers/ThemeProviders";
import { Toaster } from "react-hot-toast";
import { ToggleTheme } from "@/components/ToggleTheme";
import { Button } from "@/components/subcomponents/Buttons";
import Navbar from "@/components/ui/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProviders>
          <Toaster />
          <Navbar />
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
